import React from "react";

const CheckBackground: React.FC = () => {
  // Helper to calculate staggered begin time for animation
  const getStaggeredBegin = (index: number): string =>
    `${(index * 0.05).toFixed(2)}s`;

  return (
    <svg
      width="100%"
      height="100%"
      viewBox="0 0 1181 520"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
    >
      <g filter="url(#filter0_n_247_37)">
        {/* Vertical gradient bars - unanimated */}
        <rect
          width="5.29262"
          height="520"
          transform="translate(79.3894)"
          fill="url(#paint0_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(164.071)"
          fill="url(#paint1_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(248.753)"
          fill="url(#paint2_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(333.435)"
          fill="url(#paint3_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(418.117)"
          fill="url(#paint4_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(502.799)"
          fill="url(#paint5_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(587.481)"
          fill="url(#paint6_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(672.163)"
          fill="url(#paint7_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(756.844)"
          fill="url(#paint8_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(841.527)"
          fill="url(#paint9_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(926.209)"
          fill="url(#paint10_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(1010.89)"
          fill="url(#paint11_linear_247_37)"
        />
        <rect
          width="5.29262"
          height="520"
          transform="translate(1095.57)"
          fill="url(#paint12_linear_247_37)"
        />

        {/* Checkerboard boxes with staggered opacity animations */}
        {/* Row 0 (y=92.6208) - 14 boxes */}
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(0)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(0 92.6208)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(1)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(84.6821 92.6208)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(2)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(169.364 92.6208)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(3)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(254.046 92.6208)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(4)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(338.728 92.6208)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(5)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(423.41 92.6208)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(6)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(508.092 92.6208)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(7)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(592.774 92.6208)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(8)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(677.455 92.6208)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(9)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(762.137 92.6208)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(10)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(846.819 92.6208)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(11)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(931.501 92.6208)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(12)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1016.18 92.6208)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(13)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1100.87 92.6208)"
            fill="#131313"
          />
        </g>

        {/* Row 1 (y=177.303) */}
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(14)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(0.000244141 177.303)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(15)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(84.6821 177.303)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(16)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(169.364 177.303)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(17)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(254.046 177.303)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(18)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(338.728 177.303)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(19)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(423.41 177.303)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(20)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(508.092 177.303)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(21)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(592.774 177.303)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(22)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(677.455 177.303)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(23)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(762.137 177.303)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(24)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(846.819 177.303)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(25)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(931.501 177.303)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(26)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1016.18 177.303)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(27)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1100.87 177.303)"
            fill="#131313"
            opacity="0.75"
          />
        </g>

        {/* Row 2 (y=261.985) */}
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(28)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(0.000244141 261.985)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(29)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(84.6821 261.985)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(30)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(169.364 261.985)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(31)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(254.046 261.985)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(32)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(338.728 261.985)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(33)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(423.41 261.985)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(34)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(508.092 261.985)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(35)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(592.774 261.985)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(36)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(677.455 261.985)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(37)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(762.137 261.985)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(38)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(846.819 261.985)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(39)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(931.501 261.985)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(40)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1016.18 261.985)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(41)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1100.87 261.985)"
            fill="#131313"
            opacity="0.5"
          />
        </g>

        {/* Row 3 (y=346.667) */}
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(42)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(0.000244141 346.667)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(43)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(84.6821 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(44)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(169.364 346.667)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(45)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(254.046 346.667)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(46)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(338.728 346.667)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(47)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(423.41 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(48)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(508.092 346.667)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(49)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(592.774 346.667)"
            fill="#131313"
            opacity="0.75"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(50)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(677.455 346.667)"
            fill="#131313"
            opacity="0.5"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(51)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(762.137 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(52)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(846.819 346.667)"
            fill="#131313"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(53)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(931.501 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(54)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1016.18 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
        <g>
          <animate
            attributeName="opacity"
            dur="0.9s"
            repeatCount="indefinite"
            values="1;0.5;1"
            begin={getStaggeredBegin(55)}
          />
          <rect
            width="79.3893"
            height="79.3893"
            transform="translate(1100.87 346.667)"
            fill="#131313"
            opacity="0.25"
          />
        </g>
      </g>

      {/* Filters and gradients (unchanged) */}
      <defs>
        <filter
          id="filter0_n_247_37"
          x="0"
          y="0"
          width="1180.25"
          height="520"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          />
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.43478262424468994 0.43478262424468994"
            stitchTiles="stitch"
            numOctaves="3"
            result="noise"
            seed="3278"
          />
          <feColorMatrix
            in="noise"
            type="luminanceToAlpha"
            result="alphaNoise"
          />
          <feComponentTransfer in="alphaNoise" result="coloredNoise1">
            <feFuncA
              type="discrete"
              tableValues="1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "
            />
          </feComponentTransfer>
          <feComposite
            operator="in"
            in2="shape"
            in="coloredNoise1"
            result="noise1Clipped"
          />
          <feFlood floodColor="rgba(0, 0, 0, 0.25)" result="color1Flood" />
          <feComposite
            operator="in"
            in2="noise1Clipped"
            in="color1Flood"
            result="color1"
          />
          <feMerge result="effect1_noise_247_37">
            <feMergeNode in="shape" />
            <feMergeNode in="color1" />
          </feMerge>
        </filter>
        {/* Linear gradients (paint0 - paint12) - unchanged, abbreviated for brevity */}
        {[...Array(13)].map((_, i) => (
          <linearGradient
            key={`paint${i}_linear_247_37`}
            id={`paint${i}_linear_247_37`}
            x1="2.64631"
            y1="0"
            x2="2.64631"
            y2="520"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopOpacity="0" />
            <stop offset="0.278846" stopColor="#2B2B2B" />
            <stop offset="0.504808" stopColor="#2B2B2B" stopOpacity="0.25" />
            <stop offset="0.745192" stopColor="#2B2B2B" stopOpacity="0.5" />
            <stop offset="1" stopOpacity="0" />
          </linearGradient>
        ))}
      </defs>
    </svg>
  );
};

export default CheckBackground;
